name: "Main"

on:
  pull_request:

jobs:
  check_branch_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Content
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "LICENSE, README.md, CHANGELOG.md, CONTRIBUTING.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo Content is ok!

      - name: Check Description
        run: echo | grep -q Description README.md ; echo $?

      - name: Check Example
        run: echo | grep -q Example README.md ; echo $?

      - name: Check Installation
        run: echo | grep -q Installation README.md ; echo $?
